name: extended_phone_number_input
description: Phone input Flutter widget that supports country code, validation and contact picker
version: 1.0.1
homepage: https://github.com/WahidNasri/extended_phone_number_input

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fluttercontactpicker: ^4.6.0
  phone_numbers_parser: ^4.2.1
  form_validator: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/flags/
    - assets/countries/
    - assets/names/
